// <auto-generated />
using System;
using HOMS_MES_Extractor_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HOMS_MES_Extractor_Web.Migrations
{
    [DbContext(typeof(HOMS_MES_Extractor_WebContext))]
    [Migration("20251106062423_AddPOStatus")]
    partial class AddPOStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.PR1POL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("creator");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("line_name");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("PCStatus")
                        .HasColumnType("text")
                        .HasColumnName("pc_status");

                    b.Property<string>("PrdOrderNo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prd_order_no");

                    b.Property<string>("ProdStatus")
                        .HasColumnType("text")
                        .HasColumnName("prod_status");

                    b.Property<int>("Qty")
                        .HasColumnType("integer")
                        .HasColumnName("qty");

                    b.Property<string>("SalesOrder")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sales_order");

                    b.Property<DateTime>("TimeCreated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_created");

                    b.Property<DateTime?>("TimeUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_updated");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("WorkCenter")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_center");

                    b.HasKey("Id");

                    b.ToTable("pr_one_pol");
                });

            modelBuilder.Entity("Core.PoRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProdLine")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Summary")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("PoRecord");
                });
#pragma warning restore 612, 618
        }
    }
}
